[package]
name = "cargo-envy-safe"
version = "0.1.0"
edition = "2021"
authors = ["Sergio Pereda <sergio@adtv.io>"]
description = "Secure .env validator and encryptor"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
dirs = "6.0.0"
toml = "0.9.2"
